/**
 * CC-PILOT - Claude Code Auto Pilot
 * Copyright (c) 2026-2099 BladeX (bladejava@qq.com)
 * Licensed under the MIT License
 */
import type { Locale, CustomCategory, KnowledgeState, KnowledgeCategoryState } from '../types.js';

// ─── Category Definition ──────────────────────────────────

interface CategoryDef {
  dimensions: Record<Locale, string[]>;
  templates: Record<Locale, string[]>;
}

// ─── Built-in Categories ──────────────────────────────────

const CATEGORIES: Record<string, CategoryDef> = {
  // ── Tech (hands-on engineering topics) ──────────────────
  tech: {
    dimensions: {
      en: [
        'React hooks pitfalls (useEffect, useMemo, useCallback)',
        'TypeScript advanced types (conditional, mapped, template literal)',
        'Next.js App Router caching and revalidation',
        'Vue 3 Composition API patterns',
        'Node.js event loop and performance tuning',
        'Python asyncio concurrency patterns',
        'Go goroutine leaks and channel patterns',
        'Rust ownership and borrowing in real code',
        'Spring Boot auto-configuration internals',
        'Docker image size optimization',
        'Kubernetes deployment manifest pitfalls',
        'Nginx reverse proxy and load balancing',
        'MySQL index design and EXPLAIN reading',
        'PostgreSQL JSONB indexing and queries',
        'Redis data structure selection for real scenarios',
        'MongoDB aggregation pipeline patterns',
        'Git rebase, cherry-pick and conflict recovery',
        'microservice circuit breaker and fallback',
        'distributed lock implementations (Redis vs ZooKeeper vs etcd)',
        'cache consistency strategies (write-through, write-behind)',
        'OAuth2 vs JWT authentication design',
        'API rate limiting algorithms (token bucket, sliding window)',
        'WebSocket reconnection and heartbeat',
        'CI/CD pipeline stage design',
        'code refactoring patterns (extract, inline, replace)',
        'design patterns in real code (strategy, observer, adapter)',
        'SOLID principles applied to real code',
        'performance profiling and bottleneck localization',
      ],
      zh: [
        'React hooks 实战陷阱（useEffect/useMemo/useCallback）',
        'TypeScript 高级类型（条件类型、映射类型、模板字面量）',
        'Next.js App Router 缓存与重新验证',
        'Vue 3 Composition API 组合模式',
        'Node.js 事件循环与性能调优',
        'Python asyncio 并发模式',
        'Go goroutine 泄漏与 channel 模式',
        'Rust 所有权与借用的实战场景',
        'Spring Boot 自动配置内部机制',
        'Docker 镜像体积优化',
        'Kubernetes 部署清单常见坑',
        'Nginx 反向代理与负载均衡',
        'MySQL 索引设计与 EXPLAIN 解读',
        'PostgreSQL JSONB 索引与查询',
        'Redis 数据结构的实际场景选型',
        'MongoDB 聚合管道实战',
        'Git rebase / cherry-pick 与冲突恢复',
        '微服务熔断与降级落地',
        '分布式锁对比（Redis / ZooKeeper / etcd）',
        '缓存一致性策略（write-through / write-behind）',
        'OAuth2 与 JWT 认证方案设计',
        'API 限流算法（令牌桶 / 滑动窗口）',
        'WebSocket 重连与心跳机制',
        'CI/CD 流水线阶段设计',
        '代码重构手法（提取、内联、替换）',
        '设计模式落地（策略 / 观察者 / 适配器）',
        'SOLID 原则在真实代码中的应用',
        '性能剖析与瓶颈定位',
      ],
      ru: [
        'подводные камни React hooks (useEffect, useMemo, useCallback)',
        'продвинутые типы TypeScript (условные, mapped, template literal)',
        'кэширование и ревалидация в Next.js App Router',
        'паттерны Composition API во Vue 3',
        'Node.js event loop и оптимизация производительности',
        'паттерны конкурентности в Python asyncio',
        'утечки goroutine и паттерны каналов в Go',
        'владение и заимствование в Rust на реальном коде',
        'внутренности автоконфигурации Spring Boot',
        'оптимизация размера Docker-образа',
        'типичные ошибки в манифестах Kubernetes',
        'обратный прокси и балансировка в Nginx',
        'проектирование индексов MySQL и чтение EXPLAIN',
        'JSONB-индексы и запросы в PostgreSQL',
        'выбор структур данных Redis под реальные сценарии',
        'агрегационные пайплайны MongoDB',
        'Git rebase, cherry-pick и разрешение конфликтов',
        'circuit breaker и fallback в микросервисах',
        'распределённые блокировки (Redis vs ZooKeeper vs etcd)',
        'стратегии согласованности кэша (write-through, write-behind)',
        'проектирование аутентификации OAuth2 vs JWT',
        'алгоритмы ограничения запросов (token bucket, sliding window)',
        'переподключение и heartbeat в WebSocket',
        'проектирование этапов CI/CD пайплайна',
        'приёмы рефакторинга (extract, inline, replace)',
        'паттерны проектирования на реальном коде (стратегия, наблюдатель, адаптер)',
        'SOLID на реальном коде, а не в теории',
        'профилирование и локализация узких мест',
      ],
      de: [
        'React-Hooks-Fallstricke (useEffect, useMemo, useCallback)',
        'TypeScript fortgeschrittene Typen (conditional, mapped, template literal)',
        'Caching und Revalidierung im Next.js App Router',
        'Vue 3 Composition-API-Muster',
        'Node.js Event-Loop und Performance-Tuning',
        'Python-asyncio-Konkurrenzmuster',
        'Goroutine-Leaks und Channel-Muster in Go',
        'Rust Ownership und Borrowing im Praxiscode',
        'Spring Boot Auto-Configuration-Internas',
        'Docker-Image-Größenoptimierung',
        'typische Fehler in Kubernetes-Manifesten',
        'Nginx Reverse-Proxy und Load Balancing',
        'MySQL Index-Design und EXPLAIN lesen',
        'PostgreSQL JSONB-Indizes und Abfragen',
        'Redis-Datenstruktur-Auswahl für reale Szenarien',
        'MongoDB Aggregation-Pipeline-Muster',
        'Git Rebase, Cherry-Pick und Konfliktlösung',
        'Circuit Breaker und Fallback in Microservices',
        'verteilte Locks (Redis vs ZooKeeper vs etcd)',
        'Cache-Konsistenz-Strategien (write-through, write-behind)',
        'OAuth2 vs JWT Authentifizierung',
        'API-Rate-Limiting-Algorithmen (Token Bucket, Sliding Window)',
        'WebSocket Reconnect und Heartbeat',
        'CI/CD-Pipeline-Phasendesign',
        'Refactoring-Muster (extract, inline, replace)',
        'Entwurfsmuster im echten Code (Strategy, Observer, Adapter)',
        'SOLID angewendet, nicht theoretisch',
        'Performance-Profiling und Bottleneck-Lokalisierung',
      ],
      fr: [
        'pièges des hooks React (useEffect, useMemo, useCallback)',
        'types avancés TypeScript (conditionnels, mapped, template literal)',
        'cache et revalidation du Next.js App Router',
        'patterns Composition API Vue 3',
        'event loop Node.js et optimisation de performance',
        'patterns asyncio en Python',
        'fuites de goroutines et patterns de channels en Go',
        'ownership et borrowing Rust dans du vrai code',
        'internes de l\'auto-configuration Spring Boot',
        'optimisation de la taille des images Docker',
        'pièges des manifestes Kubernetes',
        'reverse proxy et load balancing Nginx',
        'conception d\'index MySQL et lecture d\'EXPLAIN',
        'index JSONB et requêtes PostgreSQL',
        'choix des structures Redis selon le cas',
        'patterns de pipeline d\'agrégation MongoDB',
        'Git rebase, cherry-pick et résolution de conflits',
        'circuit breaker et fallback en microservices',
        'verrous distribués (Redis vs ZooKeeper vs etcd)',
        'stratégies de cohérence de cache (write-through, write-behind)',
        'authentification OAuth2 vs JWT',
        'algorithmes de rate limiting (token bucket, sliding window)',
        'reconnexion et heartbeat WebSocket',
        'conception d\'étapes de pipeline CI/CD',
        'patterns de refactoring (extract, inline, replace)',
        'patterns de conception appliqués (strategy, observer, adapter)',
        'SOLID appliqué, pas théorique',
        'profiling de performance et localisation de goulots',
      ],
    },
    templates: {
      en: [
        'Give me a complete code example of {D} with detailed comments, then one paragraph on when to use it.',
        'List 5 common real-world pitfalls with {D}. For each: wrong code / correct code / why it matters.',
        'Show a Before/After refactoring case for {D}. Explain what improved and why.',
        'Compare 2-3 ways to implement {D}. For each: when to pick it, trade-offs, a minimal snippet.',
        'For {D}, give 3 interview questions engineers actually ask, plus high-signal answer points.',
        'Ground {D} in a real business scenario, then give minimal runnable code and extension hints.',
      ],
      zh: [
        '给我一个「{D}」的完整代码示例（附详细注释），再用一段话说明什么场景下该用。',
        '列出 5 个「{D}」在实战中常见的坑。每个给出：错误代码 / 正确代码 / 原因。',
        '给我一个「{D}」的 Before / After 重构案例，说明优化了什么、为什么。',
        '对比「{D}」的 2-3 种实现方式。每种：适用场景、取舍、最小代码片段。',
        '针对「{D}」，给 3 道工程师面试真问的题目 + 高质量答题要点。',
        '用一个真实业务场景引出「{D}」，给最小可运行代码 + 扩展点提示。',
      ],
      ru: [
        'Дай полный пример кода по теме {D} с подробными комментариями, затем одним абзацем — когда это использовать.',
        'Перечисли 5 реальных подводных камней по теме {D}. Для каждого: неправильный код / правильный код / почему это важно.',
        'Покажи кейс рефакторинга Before/After по теме {D}. Объясни, что улучшилось и почему.',
        'Сравни 2-3 способа реализации {D}. Для каждого: когда выбирать, компромиссы, минимальный сниппет.',
        'По теме {D} дай 3 вопроса, которые реально задают на собеседовании, и ключевые тезисы ответов.',
        'Привяжи {D} к реальному бизнес-сценарию, затем дай минимально рабочий код и точки расширения.',
      ],
      de: [
        'Gib ein vollständiges Codebeispiel zu {D} mit ausführlichen Kommentaren, danach einen Absatz dazu, wann man es einsetzen sollte.',
        'Nenne 5 häufige Praxisfehler bei {D}. Für jeden: falscher Code / richtiger Code / warum es wichtig ist.',
        'Zeige einen Before/After-Refactoring-Fall zu {D}. Erkläre, was sich verbessert hat und warum.',
        'Vergleiche 2-3 Umsetzungen von {D}. Für jede: Einsatz, Trade-offs, minimaler Codeausschnitt.',
        'Zu {D} gib 3 Interviewfragen, die Engineers wirklich stellen, plus prägnante Antwortpunkte.',
        'Verknüpfe {D} mit einem echten Business-Szenario und gib minimal lauffähigen Code plus Erweiterungspunkte.',
      ],
      fr: [
        'Donne un exemple de code complet de {D} avec commentaires détaillés, puis un paragraphe sur quand l\'utiliser.',
        'Liste 5 pièges fréquents en production sur {D}. Pour chacun : code erroné / code correct / pourquoi ça compte.',
        'Montre un cas de refactoring Avant/Après pour {D}. Explique ce qui s\'améliore et pourquoi.',
        'Compare 2-3 façons d\'implémenter {D}. Pour chacune : quand la choisir, compromis, extrait minimal.',
        'Pour {D}, donne 3 questions d\'entretien qu\'on pose vraiment, avec points de réponse à fort signal.',
        'Ancre {D} dans un vrai scénario métier, puis donne un code minimal exécutable et des points d\'extension.',
      ],
    },
  },

  // ── English Vocabulary (practical, scenario-based) ──────
  english: {
    dimensions: {
      en: [
        'daily small talk and greetings',
        'expressing emotions and attitudes',
        'restaurant and food ordering',
        'shopping and prices',
        'renting and neighbors',
        'doctor visits and describing symptoms',
        'airport, travel and hotel check-in',
        'business email writing',
        'meetings and presentations',
        'job interview Q&A',
        'negotiation and persuasion',
        'describing data and trends',
        'opinions, agreement and pushback',
        'polite requests and refusals',
        'make / do / have / take collocations',
        'commonly confused word pairs',
        'academic writing verbs',
      ],
      zh: [
        '日常闲聊与问候',
        '情绪与态度表达',
        '点餐与餐厅对话',
        '购物与询价',
        '租房与邻里沟通',
        '就医问诊与症状描述',
        '机场出行与酒店入住',
        '商务邮件写作',
        '会议与汇报',
        '面试问答',
        '谈判与说服',
        '描述数据与趋势',
        '观点、同意与反驳',
        '委婉请求与拒绝',
        'make / do / have / take 高频搭配',
        '常见易混淆词对',
        '学术写作高频动词',
      ],
      ru: [
        'повседневное общение и приветствия',
        'выражение эмоций и отношения',
        'ресторан и заказ еды',
        'покупки и цены',
        'аренда жилья и соседи',
        'визит к врачу и описание симптомов',
        'аэропорт, путешествия и заселение в отель',
        'деловая переписка по email',
        'совещания и презентации',
        'вопросы на собеседовании',
        'переговоры и убеждение',
        'описание данных и трендов',
        'мнение, согласие и возражение',
        'вежливые просьбы и отказы',
        'коллокации с make / do / have / take',
        'часто путаемые пары слов',
        'академические глаголы',
      ],
      de: [
        'Smalltalk und Begrüßungen',
        'Emotionen und Einstellungen ausdrücken',
        'Restaurant und Essensbestellung',
        'Einkauf und Preise',
        'Mieten und Nachbarn',
        'Arztbesuch und Symptome beschreiben',
        'Flughafen, Reisen und Hotel-Check-in',
        'Geschäftsmails schreiben',
        'Meetings und Präsentationen',
        'Vorstellungsgespräch',
        'Verhandlung und Überzeugung',
        'Daten und Trends beschreiben',
        'Meinung, Zustimmung und Widerspruch',
        'höfliche Bitten und Absagen',
        'Kollokationen mit make / do / have / take',
        'häufig verwechselte Wortpaare',
        'akademische Verben',
      ],
      fr: [
        'conversation quotidienne et salutations',
        'exprimer émotions et attitudes',
        'restaurant et commande de repas',
        'achats et prix',
        'location et voisinage',
        'consultation médicale et description des symptômes',
        'aéroport, voyages et enregistrement à l\'hôtel',
        'rédaction d\'e-mails professionnels',
        'réunions et présentations',
        'questions d\'entretien d\'embauche',
        'négociation et persuasion',
        'décrire données et tendances',
        'opinion, accord et désaccord',
        'demandes et refus polis',
        'collocations avec make / do / have / take',
        'paires de mots souvent confondus',
        'verbes académiques',
      ],
    },
    templates: {
      en: [
        'Teach me 5 practical English words or phrases about {D}. For each, give: (1) IPA pronunciation (2) plain meaning (3) a natural example sentence with translation (4) when to use it.',
        'Write a 6-8 line English dialogue set in "{D}", then list 5 key words or phrases from it, with pronunciation and native-speaker usage notes.',
        'Compare 3 pairs of commonly confused English words in the context of {D}. For each pair: the difference, a correct example, a wrong usage to avoid.',
        'Give me 5 native-sounding English expressions I can use today for {D}. For each: when to use, the exact phrase, and a softer or stronger alternative.',
        'Mini drill for {D}: 3 translation sentences (into English), then model answers and why each phrasing works.',
        'In the {D} setting, list 5 expressions native speakers use often but textbooks miss. Give example sentences and tone notes.',
      ],
      zh: [
        '教我 5 个关于「{D}」的实用英语单词或短语。每个给出：① 音标 ② 中文释义 ③ 地道例句（含中文翻译）④ 使用场景。',
        '写一段 6-8 句「{D}」场景的英文对话，然后列出其中 5 个值得学的词或短语，标注读音与地道用法。',
        '对比 3 组「{D}」场景中容易混淆的英文词，每组给出：差异、正确例句、要避免的错误用法。',
        '给我 5 个「{D}」场景可以今天就用上的地道英文表达。每条包含：使用时机、原句、替换说法（更委婉或更强硬）。',
        '针对「{D}」，给一个 mini 练习：3 个中译英句子，再给参考答案与要点解析。',
        '「{D}」场景中，母语者常用但教材少见的 5 个表达是什么？给例句并说明语气。',
      ],
      ru: [
        'Научи меня 5 практическим словам или фразам по теме {D}. Для каждого: (1) транскрипция (2) значение (3) живой пример с переводом (4) когда использовать.',
        'Напиши диалог 6-8 реплик в ситуации «{D}», затем выдели 5 полезных слов или выражений с произношением и комментариями носителя.',
        'Сравни 3 пары часто путаемых английских слов по теме {D}: разница, правильный пример, типичная ошибка.',
        'Дай 5 живых английских выражений для ситуации «{D}», которые можно использовать сегодня: когда, точная фраза, более мягкий или жёсткий вариант.',
        'Мини-упражнение по {D}: 3 фразы для перевода на английский, затем эталонные ответы с разбором.',
        'В ситуации «{D}» укажи 5 выражений, которые используют носители, но которые редко встречаются в учебниках — с примерами и пометками о тоне.',
      ],
      de: [
        'Lehre mich 5 praktische englische Wörter oder Phrasen zu {D}. Für jedes: (1) Lautschrift (2) Bedeutung (3) natürlicher Beispielsatz mit Übersetzung (4) Einsatzsituation.',
        'Schreibe einen 6-8-zeiligen englischen Dialog zu "{D}" und liste dann 5 lernenswerte Wörter oder Phrasen mit Aussprache und idiomatischer Nutzung.',
        'Vergleiche 3 Paare häufig verwechselter englischer Wörter im Kontext {D}: Unterschied, korrektes Beispiel, typischer Fehler.',
        'Gib mir 5 natürlich klingende englische Ausdrücke zu {D}, die ich heute nutzen kann: Anlass, genauer Ausdruck, sanftere oder stärkere Alternative.',
        'Mini-Übung zu {D}: 3 Sätze ins Englische übersetzen, danach Musterlösungen mit Erklärung.',
        'Im Kontext {D} nenne 5 Ausdrücke, die Muttersprachler oft nutzen, die aber in Lehrbüchern selten vorkommen — mit Beispielsätzen und Ton-Hinweisen.',
      ],
      fr: [
        'Apprends-moi 5 mots ou expressions anglais pratiques sur {D}. Pour chacun : (1) transcription API (2) sens (3) exemple naturel avec traduction (4) quand l\'utiliser.',
        'Écris un dialogue anglais de 6 à 8 répliques dans le contexte "{D}", puis liste 5 mots ou expressions à retenir avec prononciation et nuance d\'usage.',
        'Compare 3 paires de mots anglais souvent confondus dans le contexte {D} : différence, exemple correct, erreur typique.',
        'Donne-moi 5 expressions anglaises naturelles pour {D} utilisables dès aujourd\'hui : quand l\'utiliser, la phrase exacte, une variante plus douce ou plus forte.',
        'Mini-exercice sur {D} : 3 phrases à traduire en anglais, puis corrigé détaillé avec explication.',
        'Dans le contexte {D}, cite 5 expressions utilisées par les natifs mais rares dans les manuels, avec exemples et registre.',
      ],
    },
  },

  // ── Medical (specific situations and actions) ───────────
  medical: {
    dimensions: {
      en: [
        'breakfast choices that stabilize blood sugar',
        'diet and recovery after a late night',
        'neck and shoulder care for desk workers',
        'eye strain and myopia prevention',
        'distinguishing common headache types',
        'cold and flu medication pitfalls',
        'choosing between ibuprofen and acetaminophen',
        'caffeine intake and sleep quality',
        'protein intake for muscle growth',
        'real sources of dietary fiber',
        'when and how to supplement vitamin D',
        'skin barrier repair basics',
        'acne causes and daily care',
        'sunscreen: SPF tiers and correct usage',
        'early signs of high blood pressure',
        'dietary intervention for abnormal blood lipids',
        'lifestyle changes for acid reflux',
        'constipation and gut microbiome',
        'oral care details (brush, floss, mouthwash)',
        'first aid for minor cuts and burns',
        'CPR essentials for a bystander',
        'managing allergic rhinitis',
        'science-backed relief for menstrual pain',
        'anxiety and somatic symptoms',
        'self-help steps for depressed mood',
      ],
      zh: [
        '稳血糖的早餐搭配',
        '熬夜后的饮食与恢复',
        '久坐族的颈肩养护',
        '眼睛疲劳与近视预防',
        '常见头痛类型的区分',
        '感冒流感的用药误区',
        '布洛芬 vs 对乙酰氨基酚怎么选',
        '咖啡因摄入与睡眠质量',
        '蛋白质摄入与肌肉增长',
        '膳食纤维的真实来源',
        '补充维生素 D 的时机与方式',
        '皮肤屏障修复要点',
        '痤疮成因与日常护理',
        '防晒的 SPF 分级与正确用法',
        '高血压的早期信号',
        '血脂异常的饮食干预',
        '胃食管反流的生活调整',
        '便秘与肠道菌群',
        '口腔护理细节（牙刷 / 牙线 / 漱口水）',
        '小割伤烫伤的正确处理',
        '普通人可施行的心肺复苏（CPR）要点',
        '过敏性鼻炎的应对',
        '经期疼痛的科学缓解',
        '焦虑与躯体化症状',
        '抑郁情绪的自助步骤',
      ],
      ru: [
        'завтрак, стабилизирующий уровень сахара',
        'питание и восстановление после бессонной ночи',
        'уход за шеей и плечами для офисных работников',
        'усталость глаз и профилактика близорукости',
        'различение типов головной боли',
        'ошибки в приёме лекарств от простуды и гриппа',
        'выбор между ибупрофеном и парацетамолом',
        'кофеин и качество сна',
        'белок для роста мышц',
        'реальные источники пищевых волокон',
        'когда и как принимать витамин D',
        'восстановление барьера кожи',
        'причины акне и ежедневный уход',
        'солнцезащита: уровни SPF и правильное применение',
        'ранние признаки повышенного давления',
        'диетическое вмешательство при нарушении липидов',
        'образ жизни при рефлюксе',
        'запоры и микробиом кишечника',
        'детали ухода за полостью рта (щётка, нить, ополаскиватель)',
        'первая помощь при мелких порезах и ожогах',
        'основы СЛР для очевидца',
        'борьба с аллергическим ринитом',
        'научно обоснованное облегчение менструальной боли',
        'тревога и соматические симптомы',
        'шаги самопомощи при подавленном настроении',
      ],
      de: [
        'Frühstück, das den Blutzucker stabil hält',
        'Ernährung und Erholung nach einer durchzechten Nacht',
        'Nacken- und Schulterpflege für Büroarbeiter',
        'Augenbelastung und Myopie-Prävention',
        'Unterscheidung häufiger Kopfschmerzarten',
        'Fehler bei der Einnahme von Erkältungsmitteln',
        'Ibuprofen vs. Paracetamol richtig wählen',
        'Koffeinaufnahme und Schlafqualität',
        'Proteinaufnahme für Muskelaufbau',
        'echte Ballaststoffquellen',
        'Vitamin D: wann und wie supplementieren',
        'Hautbarriere reparieren: Grundlagen',
        'Akne-Ursachen und Alltagspflege',
        'Sonnenschutz: SPF-Stufen und korrekte Anwendung',
        'frühe Anzeichen von Bluthochdruck',
        'Ernährungsintervention bei Fettstoffwechselstörung',
        'Lebensstilanpassung bei Sodbrennen',
        'Verstopfung und Darmmikrobiom',
        'Mundpflege-Details (Bürste, Zahnseide, Spülung)',
        'Erste Hilfe bei kleinen Schnitten und Verbrennungen',
        'CPR-Grundlagen für Laien',
        'Umgang mit allergischer Rhinitis',
        'wissenschaftliche Linderung von Menstruationsschmerzen',
        'Angst und somatische Symptome',
        'Selbsthilfeschritte bei depressiver Stimmung',
      ],
      fr: [
        'petit-déjeuner qui stabilise la glycémie',
        'alimentation et récupération après une nuit blanche',
        'soin des cervicales pour travailleurs sédentaires',
        'fatigue oculaire et prévention de la myopie',
        'distinguer les types de maux de tête courants',
        'pièges des médicaments contre rhume et grippe',
        'choisir entre ibuprofène et paracétamol',
        'caféine et qualité du sommeil',
        'apport en protéines pour la prise de muscle',
        'vraies sources de fibres alimentaires',
        'quand et comment compléter en vitamine D',
        'réparation de la barrière cutanée',
        'causes de l\'acné et soins quotidiens',
        'protection solaire : niveaux de SPF et usage correct',
        'signes précoces d\'hypertension',
        'intervention diététique pour dyslipidémie',
        'adaptations du mode de vie pour reflux gastrique',
        'constipation et microbiote intestinal',
        'détails des soins bucco-dentaires (brosse, fil, bain)',
        'premiers secours pour coupures et brûlures légères',
        'essentiels de la RCP pour un témoin',
        'gestion de la rhinite allergique',
        'soulagement scientifique des douleurs menstruelles',
        'anxiété et symptômes somatiques',
        'étapes d\'auto-aide pour l\'humeur dépressive',
      ],
    },
    templates: {
      en: [
        'For {D}, give me 5 science-backed action items — each with a one-line "why".',
        'For {D}, list 3 common misconceptions and the correct practice, with the reasoning.',
        'For {D}, give me an executable daily checklist — morning / noon / evening / night.',
        'For {D}, which signals need action? Split into "observe first / see doctor soon / ER now".',
        'Explain the mechanism behind {D} with one analogy a non-expert can grasp.',
        'For {D}, give 5 foods or habits to favor and 5 to avoid — each with a one-line reason.',
      ],
      zh: [
        '关于「{D}」，给我 5 条有科学依据的可执行建议，每条附一句"为什么"。',
        '关于「{D}」，列 3 个常见误区 + 正确做法，说明依据。',
        '针对「{D}」，给一个一天可执行的具体清单：早 / 中 / 晚 / 夜 各做什么。',
        '关于「{D}」，哪些信号提示该就医？分"先观察 / 尽快就诊 / 立即急诊"三级。',
        '就「{D}」，解释背后的机制，用一个非专业人能懂的类比。',
        '「{D}」相关的 5 项推荐 + 5 项避免（食物或习惯），每项 1 句原因。',
      ],
      ru: [
        'По теме {D} дай 5 научно обоснованных действий — с короткой причиной для каждого.',
        'По теме {D} назови 3 распространённых заблуждения и правильную практику с обоснованием.',
        'По теме {D} составь дневной чек-лист: утро / день / вечер / ночь.',
        'По теме {D}: какие сигналы требуют реакции? Раздели на "наблюдать / к врачу скоро / срочная помощь".',
        'Объясни механизм {D} через одну аналогию, понятную не-специалисту.',
        'По теме {D} дай 5 рекомендуемых и 5 нежелательных продуктов/привычек — с одной строкой причины для каждого.',
      ],
      de: [
        'Zu {D}: gib 5 wissenschaftlich gestützte Handlungen — je mit einer kurzen Begründung.',
        'Zu {D}: 3 verbreitete Irrtümer und die richtige Praxis, mit Begründung.',
        'Zu {D}: eine umsetzbare Tagescheckliste — morgens / mittags / abends / nachts.',
        'Zu {D}: welche Signale erfordern Handeln? Einteilung in "erst beobachten / bald zum Arzt / sofort Notaufnahme".',
        'Erkläre den Mechanismus hinter {D} mit einer Analogie, die Laien verstehen.',
        'Zu {D}: 5 empfohlene und 5 zu vermeidende Lebensmittel/Gewohnheiten — je mit einem Satz Begründung.',
      ],
      fr: [
        'Sur {D}, donne-moi 5 actions étayées par la science — chacune avec un "pourquoi" d\'une ligne.',
        'Sur {D}, liste 3 idées reçues courantes et la bonne pratique avec justification.',
        'Sur {D}, donne une checklist exécutable sur une journée : matin / midi / soir / nuit.',
        'Sur {D}, quels signaux doivent déclencher une action ? Répartis en "observer / consulter bientôt / urgences immédiates".',
        'Explique le mécanisme derrière {D} avec une analogie compréhensible par un non-spécialiste.',
        'Sur {D}, 5 aliments ou habitudes à favoriser et 5 à éviter — chacun avec une ligne de raison.',
      ],
    },
  },

  // ── Legal (specific situations and actions) ─────────────
  legal: {
    dimensions: {
      en: [
        'key clauses to check in a rental lease',
        'spotting traps in second-hand home deals',
        'signing an employment contract: what to verify',
        'rights checklist when being laid off',
        'overtime pay and comp-time rules',
        'legal boundaries of a probation period',
        'validity of a non-compete agreement',
        'IP ownership: work-for-hire vs personal projects',
        'fair-use boundaries for self-media reposts',
        'responding to trademark squatting',
        'choosing a patent protection path',
        'online-shopping disputes and small claims',
        'consumer complaint procedure',
        'remedies for personal-data leaks',
        'credit card default and credit score',
        'interest-rate red lines in private lending',
        'basics of wills and inheritance',
        'property division in divorce',
        'prenuptial asset notarization',
        'child custody considerations',
        'liability determination in traffic accidents',
        'calculating personal-injury compensation',
        'elements of a defamation claim',
        'liquidated damages vs earnest money',
        'risks in corporate equity transfers',
      ],
      zh: [
        '签租房合同要重点看的条款',
        '二手房交易中的陷阱识别',
        '签劳动合同时要核对什么',
        '被裁员时的权益清单',
        '加班费与调休规则',
        '试用期的法律边界',
        '竞业协议的有效要件',
        '知识产权归属：职务作品 vs 个人作品',
        '自媒体转载的合理使用边界',
        '商标被抢注后的应对',
        '专利保护路径的选择',
        '网购纠纷与小额诉讼',
        '消费者投诉的标准流程',
        '个人信息泄露的救济途径',
        '信用卡逾期与征信',
        '民间借贷的利率红线',
        '遗嘱与继承的基本规则',
        '离婚财产分割原则',
        '婚前财产公证',
        '子女抚养权的考量因素',
        '交通事故责任认定',
        '人身损害赔偿的计算',
        '名誉侵权的构成要件',
        '合同违约金与定金的区别',
        '公司股权转让的风险点',
      ],
      ru: [
        'ключевые пункты договора аренды',
        'подводные камни сделок со вторичным жильём',
        'что проверить в трудовом договоре',
        'чек-лист прав при увольнении',
        'оплата сверхурочных и отгулы',
        'юридические границы испытательного срока',
        'действительность соглашения о неконкуренции',
        'право на результат: служебное vs личное',
        'границы добросовестного использования для блогеров',
        'ответ на сквоттинг товарного знака',
        'выбор пути патентной защиты',
        'споры с интернет-магазинами и мелкие иски',
        'процедура жалобы потребителя',
        'защита при утечке персональных данных',
        'просрочки по кредиткам и кредитная история',
        'красные линии ставок в частных займах',
        'основы завещаний и наследования',
        'раздел имущества при разводе',
        'нотариальное оформление добрачного имущества',
        'факторы при определении места жительства ребёнка',
        'определение виновника в ДТП',
        'расчёт компенсации за вред здоровью',
        'состав диффамации',
        'неустойка vs задаток',
        'риски при передаче доли в компании',
      ],
      de: [
        'wichtige Klauseln im Mietvertrag',
        'Fallen beim Gebrauchtimmobilienkauf',
        'was im Arbeitsvertrag zu prüfen ist',
        'Rechte-Checkliste bei Kündigung',
        'Überstunden und Freizeitausgleich',
        'rechtliche Grenzen der Probezeit',
        'Wirksamkeit eines Wettbewerbsverbots',
        'IP-Zuordnung: Dienst- vs Privatwerk',
        'Fair-Use-Grenzen für Social-Media-Reposts',
        'Reaktion auf Markenmissbrauch',
        'Patentschutzweg wählen',
        'Online-Shop-Streitigkeiten und Kleinforderungen',
        'Beschwerdeverfahren für Verbraucher',
        'Abhilfe bei Datenlecks',
        'Kreditkartenverzug und Bonität',
        'Zinsgrenzen bei Privatdarlehen',
        'Grundlagen von Testament und Erbfolge',
        'Vermögensaufteilung bei Scheidung',
        'Notarielle Regelung des vorehelichen Vermögens',
        'Kriterien für das Sorgerecht',
        'Haftungsfeststellung bei Verkehrsunfällen',
        'Berechnung von Schadensersatz',
        'Tatbestand der Ehrverletzung',
        'Vertragsstrafe vs Anzahlung',
        'Risiken bei Anteilsübertragungen',
      ],
      fr: [
        'clauses clés à vérifier dans un bail',
        'pièges des transactions immobilières d\'occasion',
        'signature du contrat de travail : points à vérifier',
        'checklist des droits en cas de licenciement',
        'heures supplémentaires et jours de récupération',
        'limites juridiques de la période d\'essai',
        'validité d\'une clause de non-concurrence',
        'propriété intellectuelle : travail salarié vs perso',
        'limites de l\'usage équitable pour les créateurs',
        'réponse au squat de marque',
        'choix d\'un parcours de protection par brevet',
        'litiges sur achats en ligne et petites créances',
        'procédure de plainte du consommateur',
        'recours en cas de fuite de données personnelles',
        'défaut de carte bancaire et score de crédit',
        'taux d\'usure dans les prêts privés',
        'bases du testament et de la succession',
        'partage des biens en cas de divorce',
        'notariat des biens avant mariage',
        'facteurs de garde d\'enfants',
        'détermination de responsabilité dans un accident',
        'calcul de l\'indemnisation corporelle',
        'éléments constitutifs de la diffamation',
        'clause pénale vs acompte',
        'risques de cession de parts sociales',
      ],
    },
    templates: {
      en: [
        'For {D}, give a practical checklist for an ordinary person — what to do and what to avoid.',
        'Simulate a realistic scenario that illustrates {D}, then list 3 concrete action takeaways.',
        'For {D}, list 5 clauses or details people commonly get burned on — with a one-line "why watch out".',
        'For {D}, which evidence should I collect, and at what point does collecting it pay off most?',
        'For {D}, what is the standard path when a dispute arises? (negotiate → mediate → arbitrate / sue)',
        'For {D}, pick 3 common misconceptions and correct them in plain language, with the right understanding.',
      ],
      zh: [
        '就「{D}」，给普通人的实操清单：该做什么 / 要避免什么。',
        '用一个真实模拟场景讲清「{D}」中的法律要点，再总结 3 条行动建议。',
        '关于「{D}」，列出 5 个容易被坑的条款或细节，每条附一句"为什么要警惕"。',
        '针对「{D}」，我需要哪些证据材料？在什么节点开始收集最有利？',
        '关于「{D}」，遇到纠纷的标准解决路径是什么？（协商 → 调解 → 仲裁 / 起诉）',
        '「{D}」里的 3 个常见误解，用常识语言纠正并给出正确理解。',
      ],
      ru: [
        'По теме {D} дай практический чек-лист для обычного человека — что делать и чего избегать.',
        'Смоделируй реалистичный сценарий по теме {D}, затем дай 3 конкретных вывода к действию.',
        'По теме {D} укажи 5 пунктов, на которых чаще всего обжигаются, с одной строкой "почему это важно".',
        'По теме {D}: какие доказательства собирать и когда это приносит максимальную пользу?',
        'По теме {D}: стандартный путь при споре? (переговоры → медиация → арбитраж / суд)',
        'По теме {D}: 3 распространённых заблуждения и правильное понимание простыми словами.',
      ],
      de: [
        'Zu {D}: praktische Checkliste für Laien — was tun und was vermeiden.',
        'Simuliere ein realistisches Szenario zu {D} und gib dann 3 konkrete Handlungsempfehlungen.',
        'Zu {D}: 5 Klauseln oder Details, bei denen Menschen oft draufzahlen — je mit einer Zeile "warum aufpassen".',
        'Zu {D}: welche Beweise brauche ich und wann lohnt sich deren Sammlung am meisten?',
        'Zu {D}: Standardweg im Streitfall? (verhandeln → schlichten → schiedsgerichtlich / klagen)',
        'Zu {D}: 3 verbreitete Irrtümer in einfacher Sprache korrigiert, mit korrektem Verständnis.',
      ],
      fr: [
        'Sur {D}, donne une checklist pratique pour un non-juriste : à faire / à éviter.',
        'Simule un scénario réaliste qui illustre {D}, puis liste 3 actions concrètes à retenir.',
        'Sur {D}, liste 5 clauses ou détails qui piègent souvent, chacun avec une ligne "pourquoi se méfier".',
        'Sur {D}, quelles preuves rassembler et à quel moment les collecter est le plus rentable ?',
        'Sur {D}, quel est le parcours standard en cas de litige ? (négocier → médiation → arbitrage / procès)',
        'Sur {D}, 3 idées reçues corrigées en langage courant, avec la bonne compréhension.',
      ],
    },
  },

  // ── Psychology (specific biases and techniques) ─────────
  psychology: {
    dimensions: {
      en: [
        'confirmation bias (seeing only supporting evidence)',
        'sunk cost fallacy',
        'anchoring effect (the first number wins)',
        'availability bias',
        'Dunning-Kruger effect',
        'planning fallacy (always underestimating time)',
        'Pomodoro technique in practice',
        '5-minute starter rule (beating procrastination)',
        'habit stacking (attaching new to old habits)',
        'environment design to shift behavior',
        'Nonviolent Communication 4 steps (observation / feeling / need / request)',
        'I-messages in conflict',
        'active listening techniques',
        'ABC model of emotions',
        'cognitive reappraisal for anxiety',
        'self-guided exposure for fear',
        '3-minute mindful breathing',
        'gratitude journal practice',
        'SMART goal setting',
        'intrinsic vs extrinsic motivation',
        'growth mindset at work',
        'conditions for entering flow',
        'social comparison trap (phone scrolling anxiety)',
        'managing decision fatigue',
        'spaced repetition for memory',
        'breaking rumination loops',
        'self-compassion: three elements',
      ],
      zh: [
        '确认偏误（只看支持自己的证据）',
        '沉没成本谬误',
        '锚定效应（第一个数字赢）',
        '可得性偏差',
        '邓宁-克鲁格效应',
        '规划谬误（总低估时间）',
        '番茄工作法落地',
        '5 分钟启动法（克服拖延）',
        '习惯叠加（把新习惯接在老习惯后）',
        '环境设计改变行为',
        '非暴力沟通四步（观察 / 感受 / 需要 / 请求）',
        'I-message 表达冲突',
        '积极倾听技巧',
        '情绪 ABC 模型',
        '认知重评应对焦虑',
        '自助式暴露疗法',
        '3 分钟正念呼吸',
        '感恩日记实践',
        'SMART 目标设定',
        '内在动机 vs 外在动机',
        '工作中的成长型思维',
        '进入心流的条件',
        '社交对比陷阱（刷手机焦虑）',
        '决策疲劳管理',
        '间隔重复与记忆',
        '打破反刍思维',
        '自我同情三要素',
      ],
      ru: [
        'предвзятость подтверждения (видим только подтверждающее)',
        'ошибка невозвратных затрат',
        'эффект якорения (первое число побеждает)',
        'эвристика доступности',
        'эффект Даннинга-Крюгера',
        'ошибка планирования (недооценка времени)',
        'техника Помодоро на практике',
        'правило 5 минут против прокрастинации',
        'наслоение привычек (новая к старой)',
        'дизайн среды для смены поведения',
        'ненасильственное общение: 4 шага (наблюдение / чувство / потребность / просьба)',
        'Я-сообщения в конфликте',
        'техники активного слушания',
        'ABC-модель эмоций',
        'когнитивная переоценка при тревоге',
        'самостоятельная экспозиция страхов',
        '3-минутное осознанное дыхание',
        'практика дневника благодарности',
        'постановка SMART-целей',
        'внутренняя vs внешняя мотивация',
        'установка на рост на работе',
        'условия входа в поток',
        'ловушка социального сравнения (тревога от ленты)',
        'управление усталостью от решений',
        'интервальное повторение для памяти',
        'прерывание руминативных мыслей',
        'самосострадание: три элемента',
      ],
      de: [
        'Bestätigungsfehler (nur stützende Belege sehen)',
        'Sunk-Cost-Fallacy',
        'Ankereffekt (die erste Zahl gewinnt)',
        'Verfügbarkeitsheuristik',
        'Dunning-Kruger-Effekt',
        'Planungsfehlschluss (Zeit wird unterschätzt)',
        'Pomodoro-Technik in der Praxis',
        '5-Minuten-Starterregel gegen Prokrastination',
        'Habit Stacking (neue an alte Gewohnheit koppeln)',
        'Umgebungsdesign zur Verhaltensänderung',
        'Gewaltfreie Kommunikation: 4 Schritte (Beobachten / Fühlen / Bedürfnis / Bitte)',
        'Ich-Botschaften im Konflikt',
        'aktives Zuhören — Techniken',
        'ABC-Modell der Emotionen',
        'kognitive Neubewertung bei Angst',
        'Selbsthilfe-Exposition bei Ängsten',
        '3-Minuten-Atemmeditation',
        'Dankbarkeitsjournal',
        'SMART-Ziele setzen',
        'intrinsische vs extrinsische Motivation',
        'Growth Mindset am Arbeitsplatz',
        'Bedingungen, um in Flow zu kommen',
        'Falle des sozialen Vergleichs (Scroll-Angst)',
        'Entscheidungsmüdigkeit managen',
        'Spaced Repetition fürs Gedächtnis',
        'Grübelschleifen unterbrechen',
        'Selbstmitgefühl: drei Elemente',
      ],
      fr: [
        'biais de confirmation (ne voir que les preuves favorables)',
        'erreur des coûts irrécupérables',
        'effet d\'ancrage (le premier chiffre l\'emporte)',
        'heuristique de disponibilité',
        'effet Dunning-Kruger',
        'biais de planification (sous-estimation du temps)',
        'technique Pomodoro en pratique',
        'règle des 5 minutes contre la procrastination',
        'empilement d\'habitudes (nouvelle sur ancienne)',
        'design de l\'environnement pour changer un comportement',
        'CNV en 4 étapes (observation / sentiment / besoin / demande)',
        'messages-je en conflit',
        'techniques d\'écoute active',
        'modèle ABC des émotions',
        'réévaluation cognitive face à l\'anxiété',
        'exposition auto-guidée face aux peurs',
        'respiration consciente 3 minutes',
        'pratique du journal de gratitude',
        'objectifs SMART',
        'motivation intrinsèque vs extrinsèque',
        'état d\'esprit de croissance au travail',
        'conditions d\'entrée dans le flow',
        'piège de la comparaison sociale (anxiété du scroll)',
        'gérer la fatigue décisionnelle',
        'répétition espacée pour la mémoire',
        'briser les boucles de rumination',
        'auto-compassion : trois éléments',
      ],
    },
    templates: {
      en: [
        'Explain {D}: open with a daily scenario, then give one exercise I can try in under 5 minutes.',
        'How does {D} show up in work, in relationships, and in self-management? Give one countermove for each.',
        'For {D}: 3 signals that I\'m doing it (self-check) and the corresponding corrective move.',
        'What research or classic experiment underpins {D}? What does the finding imply for my daily decisions?',
        'Give a 7-day practice plan based on {D} — one concrete action per day.',
        'For {D}, what is the common misuse? Where is the right boundary for applying it?',
      ],
      zh: [
        '解释「{D}」：先用一个日常场景引入，再给一个 5 分钟内可以试的小练习。',
        '「{D}」在工作 / 亲密关系 / 自我管理中各有一个典型表现，分别怎么应对？',
        '关于「{D}」，给 3 个识别信号（自测有没有在做）+ 对应纠正方法。',
        '「{D}」背后的研究或经典实验是什么？结论对我日常决策的启示是？',
        '基于「{D}」给一个 7 天练习计划，每天一个具体动作。',
        '「{D}」常见的误用是什么？正确用法和边界在哪里？',
      ],
      ru: [
        'Объясни {D}: начни с бытового сценария, затем дай упражнение, которое можно сделать за 5 минут.',
        'Как {D} проявляется на работе, в отношениях и в самоуправлении? Дай один контршаг для каждого.',
        'По теме {D} дай 3 сигнала, что я это делаю (самопроверка) и соответствующий корректирующий шаг.',
        'Какое исследование или классический эксперимент лежит в основе {D}? Какой вывод для повседневных решений?',
        'Дай 7-дневный план практики по {D} — по одному конкретному действию в день.',
        'По теме {D}: что является распространённым неправильным применением? Где правильная граница?',
      ],
      de: [
        'Erkläre {D}: beginne mit einem Alltagsszenario, dann gib eine Übung, die in unter 5 Minuten machbar ist.',
        'Wie zeigt sich {D} bei Arbeit, Beziehungen und Selbstmanagement? Je ein Gegenzug.',
        'Zu {D}: 3 Signale, dass ich es gerade tue (Selbstcheck), plus korrigierender Schritt.',
        'Welches Forschungsergebnis oder klassische Experiment stützt {D}? Was bedeutet das für meine Alltagsentscheidungen?',
        'Gib einen 7-Tage-Praxisplan basierend auf {D} — je eine konkrete Handlung pro Tag.',
        'Zu {D}: was ist häufiger Missbrauch? Wo ist die korrekte Anwendungsgrenze?',
      ],
      fr: [
        'Explique {D} : démarre par un scénario quotidien, puis donne un exercice réalisable en moins de 5 minutes.',
        'Comment {D} se manifeste au travail, en couple et en gestion de soi ? Une contre-mesure pour chacun.',
        'Sur {D} : 3 signaux que je suis en train de le faire (auto-test) et la correction correspondante.',
        'Quelle recherche ou expérience classique étaie {D} ? Qu\'en tirer pour les décisions quotidiennes ?',
        'Donne un plan de pratique de 7 jours basé sur {D} — une action concrète par jour.',
        'Sur {D} : quel est le mésusage courant ? Où se trouve la bonne limite d\'application ?',
      ],
    },
  },

  // ── History (specific events and turning points) ────────
  history: {
    dimensions: {
      en: [
        'Roman Republic to Empire transition',
        'Silk Road goods and cultural exchange',
        'Mongol Empire military organization',
        'Black Death aftermath in Europe',
        'technological breakthroughs behind the Age of Exploration',
        'Renaissance masters and the patron system',
        'social and economic roots of the Reformation',
        'child labor and legislation in the Industrial Revolution',
        'key battles of the American Revolution',
        'phases and turning points of the French Revolution',
        'what decided the Napoleonic Wars',
        'international backdrop of the Opium Wars',
        'rise and fall of the Taiping Rebellion',
        'core reforms of the Meiji Restoration',
        'how WWI actually started',
        'hidden flaws of the Versailles system',
        'causes of the Great Depression and the New Deal',
        'decisive battles of the European WWII theater',
        'Pacific WWII turning points',
        'Cuban Missile Crisis during the Cold War',
        'rise and fall of the Berlin Wall',
        'Apollo program: tech and politics',
        'land vs maritime Silk Roads compared',
        'institutional innovations of the Qin centralized state',
        'Tang dynasty openness in practice',
        'Song commercial economy and inventions',
        'Yuan influence across Eurasia',
        'Ming sea-ban vs Zheng He voyages paradox',
        'gains and losses of the late Qing Self-Strengthening Movement',
        'multiple causes of the Soviet collapse',
      ],
      zh: [
        '罗马共和国向帝国的转变',
        '丝绸之路上的商品与文化交流',
        '蒙古帝国的军事组织',
        '黑死病对欧洲的深远影响',
        '大航海时代背后的技术突破',
        '文艺复兴三杰与赞助人制度',
        '宗教改革的社会经济动因',
        '工业革命中的童工与立法',
        '美国独立战争的关键战役',
        '法国大革命的阶段与转折',
        '拿破仑战争的胜负关键',
        '鸦片战争的国际背景',
        '太平天国运动的成败',
        '明治维新的核心改革',
        '第一次世界大战的爆发机制',
        '凡尔赛体系的隐患',
        '大萧条的成因与罗斯福新政',
        '二战欧洲战场关键战役',
        '二战太平洋战场转折点',
        '冷战中的古巴导弹危机',
        '柏林墙的建立与倒塌',
        '阿波罗登月计划的技术与政治',
        '陆上与海上丝绸之路对比',
        '秦朝中央集权的制度创新',
        '唐代对外开放的表现',
        '宋代商品经济与技术发明',
        '元朝对欧亚的影响',
        '明朝海禁与郑和下西洋悖论',
        '清末洋务运动的得失',
        '苏联解体的多重原因',
      ],
      ru: [
        'переход Римской республики к империи',
        'товары и культурный обмен на Шёлковом пути',
        'военная организация Монгольской империи',
        'последствия Чёрной смерти в Европе',
        'технологические прорывы эпохи Великих открытий',
        'мастера Ренессанса и система меценатства',
        'социально-экономические корни Реформации',
        'детский труд и законодательство промышленной революции',
        'ключевые сражения Войны за независимость США',
        'этапы и повороты Французской революции',
        'что решило исход наполеоновских войн',
        'международный фон Опиумных войн',
        'взлёт и падение Тайпинского восстания',
        'ключевые реформы Мэйдзи',
        'как на самом деле началась Первая мировая',
        'скрытые изъяны Версальской системы',
        'причины Великой депрессии и Новый курс',
        'решающие сражения европейского театра Второй мировой',
        'переломные моменты тихоокеанского театра',
        'Карибский кризис холодной войны',
        'возведение и падение Берлинской стены',
        'программа Аполлон: техника и политика',
        'сравнение сухопутного и морского Шёлкового пути',
        'институциональные новации империи Цинь',
        'открытость Тан на практике',
        'товарная экономика Сун и изобретения',
        'влияние Юань на Евразию',
        'парадокс морского запрета Мин и походов Чжэн Хэ',
        'итоги движения самоусиления позднего Цин',
        'многофакторные причины распада СССР',
      ],
      de: [
        'Übergang der Römischen Republik zum Kaiserreich',
        'Waren und Kulturaustausch auf der Seidenstraße',
        'militärische Organisation des Mongolenreichs',
        'Nachwirkungen der Pest in Europa',
        'technische Durchbrüche hinter dem Entdeckungszeitalter',
        'Renaissance-Meister und das Mäzenatensystem',
        'sozioökonomische Wurzeln der Reformation',
        'Kinderarbeit und Gesetzgebung der Industriellen Revolution',
        'entscheidende Schlachten des Amerikanischen Unabhängigkeitskriegs',
        'Phasen und Wendepunkte der Französischen Revolution',
        'was die Napoleonischen Kriege entschied',
        'internationaler Hintergrund der Opiumkriege',
        'Aufstieg und Fall des Taiping-Aufstands',
        'Kernreformen der Meiji-Restauration',
        'wie der Erste Weltkrieg tatsächlich begann',
        'verborgene Schwächen der Versailler Ordnung',
        'Ursachen der Großen Depression und der New Deal',
        'entscheidende Schlachten des europäischen WK2-Schauplatzes',
        'Wendepunkte im Pazifikkrieg',
        'Kubakrise im Kalten Krieg',
        'Bau und Fall der Berliner Mauer',
        'Apollo-Programm: Technik und Politik',
        'Land- und Seeroute der Seidenstraße im Vergleich',
        'institutionelle Innovationen des Qin-Zentralstaats',
        'Öffnung der Tang-Dynastie in der Praxis',
        'Warenwirtschaft und Erfindungen der Song',
        'Einfluss der Yuan auf Eurasien',
        'Paradox zwischen Ming-Seeverbot und Zheng Hes Reisen',
        'Gewinne und Verluste der Selbststärkungsbewegung des späten Qing',
        'multiple Ursachen des Zusammenbruchs der Sowjetunion',
      ],
      fr: [
        'transition de la République romaine à l\'Empire',
        'marchandises et échanges culturels sur la Route de la soie',
        'organisation militaire de l\'Empire mongol',
        'conséquences de la peste noire en Europe',
        'percées techniques derrière les grandes découvertes',
        'maîtres de la Renaissance et système de mécénat',
        'racines socio-économiques de la Réforme',
        'travail des enfants et législation de la révolution industrielle',
        'batailles clés de la guerre d\'indépendance américaine',
        'phases et tournants de la Révolution française',
        'ce qui a décidé les guerres napoléoniennes',
        'contexte international des guerres de l\'opium',
        'ascension et chute du soulèvement Taiping',
        'réformes clés de l\'ère Meiji',
        'comment la Première Guerre a vraiment éclaté',
        'failles cachées du système de Versailles',
        'causes de la Grande Dépression et New Deal',
        'batailles décisives du théâtre européen de la Seconde Guerre',
        'tournants du théâtre du Pacifique',
        'crise des missiles de Cuba durant la guerre froide',
        'construction et chute du mur de Berlin',
        'programme Apollo : technique et politique',
        'comparaison Route de la soie terrestre et maritime',
        'innovations institutionnelles du Qin centralisé',
        'ouverture Tang en pratique',
        'économie marchande et inventions sous les Song',
        'influence des Yuan sur l\'Eurasie',
        'paradoxe des interdictions maritimes Ming et des voyages de Zheng He',
        'gains et pertes du mouvement d\'auto-renforcement de la fin des Qing',
        'causes multiples de l\'effondrement de l\'URSS',
      ],
    },
    templates: {
      en: [
        'For {D}: walk through cause → process → outcome along a clear timeline (2-3 sentences per phase).',
        'In {D}, who were the key figures and what did each of their decisions actually change?',
        'What institutional / cultural / territorial legacies did {D} leave on today\'s world?',
        'Counterfactual on {D}: if one variable had shifted, how might history have gone? Give one alternative run.',
        'The pop narrative of {D} (films, textbooks) differs from history in 2-3 specific ways — which ones?',
        'Compare {D} with another similar event. At the institutional level, what is the same and what differs?',
      ],
      zh: [
        '关于「{D}」：按时间线讲清前因 → 过程 → 结果（每个阶段 2-3 句）。',
        '「{D}」中，关键人物有哪些？他们的每个决策实际上改变了什么？',
        '「{D}」在制度 / 文化 / 版图层面给今天的世界留下了哪些遗产？',
        '对「{D}」做一次反事实推演：如果改变一个变量，历史可能怎么走？给一个替代版本。',
        '「{D}」的流行叙事（电影 / 教科书）与史实有哪 2-3 处出入？具体是什么？',
        '把「{D}」与另一个类似事件对比，制度层面的异同是什么？',
      ],
      ru: [
        'По теме {D}: разложи по таймлайну причина → процесс → результат (2-3 предложения на фазу).',
        'Кто ключевые фигуры в {D}? Что именно изменило каждое их решение?',
        'Какое институциональное / культурное / территориальное наследие {D} ощущается сегодня?',
        'Контрфактический анализ {D}: если бы изменилась одна переменная, как бы пошла история? Дай один альтернативный сценарий.',
        'Популярный нарратив о {D} (фильмы, учебники) расходится с фактами в 2-3 конкретных местах — в каких?',
        'Сравни {D} с аналогичным событием. Что общего и чем отличаются на уровне институтов?',
      ],
      de: [
        'Zu {D}: zeichne entlang einer klaren Zeitleiste Ursache → Verlauf → Ergebnis nach (2-3 Sätze pro Phase).',
        'Wer sind die Schlüsselfiguren in {D}? Was hat jede ihrer Entscheidungen konkret verändert?',
        'Welche institutionellen / kulturellen / territorialen Erbe hinterließ {D} der heutigen Welt?',
        'Kontrafaktisch zu {D}: wie wäre die Geschichte verlaufen, wenn eine Variable anders gewesen wäre? Gib einen Alternativverlauf.',
        'Das Pop-Narrativ zu {D} (Filme, Schulbücher) weicht in 2-3 konkreten Punkten von der Geschichte ab — welchen?',
        'Vergleiche {D} mit einem ähnlichen Ereignis. Was ist institutionell gleich, was unterscheidet sich?',
      ],
      fr: [
        'Sur {D} : déroule cause → déroulement → conséquence sur une chronologie claire (2-3 phrases par phase).',
        'Dans {D}, qui sont les figures clés et qu\'a changé concrètement chacune de leurs décisions ?',
        'Quels héritages institutionnels / culturels / territoriaux {D} a-t-il laissés au monde actuel ?',
        'Contrefactuel sur {D} : si une variable avait changé, comment l\'histoire aurait-elle pu aller ? Donne une version alternative.',
        'Le récit populaire de {D} (films, manuels) diverge des faits sur 2-3 points précis — lesquels ?',
        'Compare {D} avec un autre événement similaire. Sur le plan institutionnel, quels points communs et différences ?',
      ],
    },
  },
};

// ─── Generic Templates (for custom categories) ───────────

const GENERIC_TEMPLATES: Record<Locale, string[]> = {
  en: [
    'Teach me something interesting about {C}, focusing on {D}.',
    'What is a useful concept in {C} that most people don\'t know?',
    'Give a practical tip related to {C}.',
    'What is a common misconception about {C}?',
    'Explain a key principle of {C} with an example.',
    'What is the most important thing a beginner should know about {C}?',
    'Share a surprising fact about {C}.',
    'How can knowledge of {C} be applied in everyday life?',
  ],
  zh: [
    '教我一个关于「{C}」的有趣知识，侧重于{D}。',
    '「{C}」领域有什么大多数人不知道的实用概念？',
    '给一个与「{C}」相关的实用建议。',
    '关于「{C}」有什么常见误区？',
    '用一个例子解释「{C}」的关键原则。',
    '初学者最应该了解「{C}」的什么？',
    '分享一个关于「{C}」的冷知识。',
    '「{C}」的知识如何应用到日常生活中？',
  ],
  ru: [
    'Расскажи что-то интересное о {C}, с акцентом на {D}.',
    'Какой полезный факт о {C} мало кто знает?',
    'Дай практический совет по {C}.',
    'Какое распространённое заблуждение связано с {C}?',
    'Объясни ключевой принцип {C} на примере.',
    'Что важнее всего знать новичку в {C}?',
    'Поделись удивительным фактом о {C}.',
    'Как знания о {C} можно применить в повседневной жизни?',
  ],
  de: [
    'Erzähle mir etwas Interessantes über {C}, mit Fokus auf {D}.',
    'Welches nützliche Konzept in {C} kennen die wenigsten?',
    'Gib einen praktischen Tipp zu {C}.',
    'Welches verbreitete Missverständnis gibt es über {C}?',
    'Erkläre ein Schlüsselprinzip von {C} mit einem Beispiel.',
    'Was sollte ein Anfänger über {C} wissen?',
    'Teile einen überraschenden Fakt über {C}.',
    'Wie kann Wissen über {C} im Alltag angewendet werden?',
  ],
  fr: [
    'Apprends-moi quelque chose d\'intéressant sur {C}, en lien avec {D}.',
    'Quel concept utile de {C} est peu connu ?',
    'Donne un conseil pratique sur {C}.',
    'Quelle idée reçue courante existe sur {C} ?',
    'Explique un principe clé de {C} avec un exemple.',
    'Que devrait savoir un débutant sur {C} ?',
    'Partage un fait surprenant sur {C}.',
    'Comment appliquer les connaissances de {C} au quotidien ?',
  ],
};

// ─── Shuffle Engine ───────────────────────────────────────

function fisherYatesShuffle(arr: number[]): number[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function generateShuffledIndices(count: number): number[] {
  return fisherYatesShuffle(Array.from({ length: count }, (_, i) => i));
}

function ensureCategoryState(
  state: KnowledgeState,
  categoryId: string,
  comboCount: number,
): KnowledgeCategoryState {
  const existing = state.categories[categoryId];
  if (existing && existing.shuffledIndices.length === comboCount && existing.cursor < comboCount) {
    return existing;
  }
  // Initialize or reshuffle when exhausted / size changed
  return {
    shuffledIndices: generateShuffledIndices(comboCount),
    cursor: 0,
    recentDimensions: existing?.recentDimensions ?? [],
  };
}

function pushRecent(arr: string[], item: string, max = 10): string[] {
  const next = [...arr.filter(d => d !== item), item];
  return next.length > max ? next.slice(next.length - max) : next;
}

// ─── Prompt Builder ───────────────────────────────────────

function buildBuiltinPrompt(
  categoryId: string,
  locale: Locale,
  catState: KnowledgeCategoryState,
): { prompt: string; dimension: string } {
  const cat = CATEGORIES[categoryId];
  const dims = cat.dimensions[locale] ?? cat.dimensions.en;
  const tpls = cat.templates[locale] ?? cat.templates.en;
  const comboIdx = catState.shuffledIndices[catState.cursor];
  const dimIdx = comboIdx % dims.length;
  const tplIdx = Math.floor(comboIdx / dims.length);
  const dimension = dims[dimIdx];
  const template = tpls[tplIdx % tpls.length];
  let prompt = template.replace('{D}', dimension);

  // Anti-repeat context hint
  if (catState.recentDimensions.length > 0) {
    const recentHint = catState.recentDimensions.slice(-5).join(', ');
    const hint = locale === 'zh'
      ? `（请避免与以下最近话题重复：${recentHint}）`
      : locale === 'ru'
        ? `(Избегай пересечения с недавними темами: ${recentHint})`
        : locale === 'de'
          ? `(Vermeide Überschneidungen mit diesen Themen: ${recentHint})`
          : locale === 'fr'
            ? `(Évite de répéter ces sujets récents : ${recentHint})`
            : `(Avoid overlapping with these recent topics: ${recentHint})`;
    prompt += ' ' + hint;
  }

  return { prompt, dimension };
}

function buildCustomPrompt(
  custom: CustomCategory,
  locale: Locale,
  catState: KnowledgeCategoryState,
): { prompt: string; dimension: string } {
  const tpls = GENERIC_TEMPLATES[locale] ?? GENERIC_TEMPLATES.en;
  const tplIdx = catState.shuffledIndices[catState.cursor] % tpls.length;
  const template = tpls[tplIdx];
  const dimension = custom.name;
  let prompt = template.replace('{C}', custom.name).replace('{D}', custom.description || custom.name);

  if (catState.recentDimensions.length > 0) {
    const recentHint = catState.recentDimensions.slice(-5).join(', ');
    const hint = locale === 'zh'
      ? `（请避免与以下最近话题重复：${recentHint}）`
      : `(Avoid overlapping with these recent topics: ${recentHint})`;
    prompt += ' ' + hint;
  }

  return { prompt, dimension };
}

// ─── Public API ───────────────────────────────────────────

export function isBuiltinCategory(id: string): boolean {
  return id in CATEGORIES;
}

export function getBuiltinCategoryIds(): string[] {
  return Object.keys(CATEGORIES);
}

export function pickKnowledgePrompt(
  state: KnowledgeState,
  enabledCategories: string[],
  customCategories: CustomCategory[],
  locale: Locale,
): { prompt: string; updatedState: KnowledgeState } {
  if (enabledCategories.length === 0) {
    enabledCategories = ['tech'];
  }

  // Pick a random enabled category
  const categoryId = enabledCategories[Math.floor(Math.random() * enabledCategories.length)];
  const isBuiltin = isBuiltinCategory(categoryId);
  const customDef = customCategories.find(c => c.id === categoryId);

  // Determine combo count
  let comboCount: number;
  if (isBuiltin) {
    const cat = CATEGORIES[categoryId];
    const dims = cat.dimensions[locale] ?? cat.dimensions.en;
    const tpls = cat.templates[locale] ?? cat.templates.en;
    comboCount = dims.length * tpls.length;
  } else {
    const tpls = GENERIC_TEMPLATES[locale] ?? GENERIC_TEMPLATES.en;
    comboCount = tpls.length;
  }

  // Ensure category state
  const updatedState: KnowledgeState = {
    categories: { ...state.categories },
  };
  const catState = ensureCategoryState(updatedState, categoryId, comboCount);

  // Build prompt
  let prompt: string;
  let dimension: string;

  if (isBuiltin) {
    ({ prompt, dimension } = buildBuiltinPrompt(categoryId, locale, catState));
  } else if (customDef) {
    ({ prompt, dimension } = buildCustomPrompt(customDef, locale, catState));
  } else {
    // Fallback: unknown category, treat as custom with minimal info
    ({ prompt, dimension } = buildCustomPrompt(
      { id: categoryId, name: categoryId, description: categoryId },
      locale,
      catState,
    ));
  }

  // Advance cursor and update recent dimensions
  updatedState.categories[categoryId] = {
    shuffledIndices: catState.shuffledIndices,
    cursor: catState.cursor + 1 >= comboCount ? 0 : catState.cursor + 1,
    recentDimensions: pushRecent(catState.recentDimensions, dimension),
  };

  // Reshuffle if cursor wrapped
  if (catState.cursor + 1 >= comboCount) {
    updatedState.categories[categoryId].shuffledIndices = generateShuffledIndices(comboCount);
  }

  return { prompt, updatedState };
}
